import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useMoralis } from 'react-moralis'
import Login from "../components/Login"
export default function Home() {
  
  const {isAuthenticated,logout}=useMoralis();
  if(!isAuthenticated) return <Login/>;
  return (
    <div className="h-screen">
      <Head>
        <title>Metaverse Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>welcome</h1>
      <div>
        <div className="max-w-screen-2xl mx-auto"></div>
      </div>
      <button  onClick={logout}>Logout</button>
    </div>
  );
}
