import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useMoralis } from 'react-moralis'
import Login from "../components/Login"
export default function Home() {
  
  const {isAuth,logout}=useMoralis();
  if(!isAuth) {return <Login/>}
  return (
    <div className="h-screen">
      <Head>
        <title>Metaverse Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>welcome</h1>
      
      <button onClick={logout}>Logout</button>
    </div>
  );
}
