import Image from "next/image"
import Head from "next/head"
import {useMoralis} from 'react-moralis'
function Login() {
    
    const {authenticate}= useMoralis();
    return (

        <div>
            <Head>
        <title>Metaverse Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./icon.ico"  />
      </Head>
            <div className="flex flex-col absolute z-50 h-4/6 items-center justify-center w-full space-y-4">
            <Image
            className="object-cover rounded-full"
            src="https://raw.githubusercontent.com/hiverkiya/Metaverse-Media/main/metaverse-media/media/profile.jpg"
            height={200}
            width={200}
            />
            <button 
            onClick={ authenticate}
            className="bg-red-500 rounded-lg p-5 font-bold text-lg  animate-pulse">LOGIN TO METAVERSE MEDIA</button>
            </div>

            <div className="w-full h-screen ">
            <Image
            src="https://raw.githubusercontent.com/hiverkiya/Metaverse-Media/main/metaverse-media/media/background.jpg"
            layout="fill"
            objectFit="cover"
            
            />
            </div>
        </div>
    )
}

export default Login
